#!/usr/bin/env node
/**
 * scripts/measure-schema.mjs
 *
 * P12-026: Schema measurement.
 *
 * Exit criterion:
 *   "The real schema measured: models, fields, relations, indexes, file sizes, generated size.
 *    Every measurement is reproducible by command and tracked over time."
 *
 * Capabilities:
 *   1. Measures every schema part in unierp-data/prisma/schema/*.prisma and unierp-corporate-website.
 *   2. Extracts metrics: totalModels, totalFields, totalRelations, totalIndexes, totalEnums, totalLines, fileBreakdown.
 *   3. Generates docs/programme/P12-026-SCHEMA-MEASUREMENT.json and docs/programme/P12-026-SCHEMA-MEASUREMENT.md.
 *   4. Verifies measurements are reproducible and not drifting.
 *
 * Usage:
 *   node scripts/measure-schema.mjs --generate
 *   node scripts/measure-schema.mjs --verify
 */

import { readFileSync, writeFileSync, existsSync, readdirSync, statSync } from "node:fs";
import { resolve, dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const WORKSPACE_DIR = resolve(__dirname, "..");
const PARENT_DIR = resolve(WORKSPACE_DIR, "..");
const DATA_SCHEMA_DIR = resolve(PARENT_DIR, "unierp-data/prisma/schema");

const JSON_OUT = resolve(WORKSPACE_DIR, "docs/programme/P12-026-SCHEMA-MEASUREMENT.json");
const MD_OUT = resolve(WORKSPACE_DIR, "docs/programme/P12-026-SCHEMA-MEASUREMENT.md");

export function measureEstateSchema() {
  if (!existsSync(DATA_SCHEMA_DIR)) {
    throw new Error(`Data schema directory not found: ${DATA_SCHEMA_DIR}`);
  }

  const files = readdirSync(DATA_SCHEMA_DIR)
    .filter((f) => f.endsWith(".prisma"))
    .sort();

  const fileMetrics = {};
  let totalModels = 0;
  let totalFields = 0;
  let totalRelations = 0;
  let totalIndexes = 0;
  let totalEnums = 0;
  let totalLines = 0;
  let totalBytes = 0;

  for (const f of files) {
    const filePath = join(DATA_SCHEMA_DIR, f);
    const content = readFileSync(filePath, "utf8");
    const stat = statSync(filePath);
    const lines = content.split("\n");

    let modelsInFile = 0;
    let fieldsInFile = 0;
    let relationsInFile = 0;
    let indexesInFile = 0;
    let enumsInFile = 0;

    let inModel = false;

    for (const rawLine of lines) {
      const line = rawLine.trim();
      if (line.startsWith("model ")) {
        inModel = true;
        modelsInFile++;
        totalModels++;
        continue;
      }
      if (line.startsWith("enum ")) {
        enumsInFile++;
        totalEnums++;
        continue;
      }
      if (line === "}") {
        inModel = false;
        continue;
      }
      if (inModel) {
        if (line.startsWith("@@index") || line.startsWith("@@unique") || line.startsWith("@@id")) {
          indexesInFile++;
          totalIndexes++;
        } else if (line.length > 0 && !line.startsWith("//") && !line.startsWith("@@")) {
          fieldsInFile++;
          totalFields++;
          if (line.includes("@relation(")) {
            relationsInFile++;
            totalRelations++;
          }
        }
      }
    }

    totalLines += lines.length;
    totalBytes += stat.size;

    fileMetrics[f] = {
      lines: lines.length,
      bytes: stat.size,
      models: modelsInFile,
      fields: fieldsInFile,
      relations: relationsInFile,
      indexes: indexesInFile,
      enums: enumsInFile,
    };
  }

  return {
    generatedAt: new Date().toISOString(),
    phase: "P12-026",
    summary: {
      totalFiles: files.length,
      totalLines,
      totalBytes,
      totalModels,
      totalFields,
      totalRelations,
      totalIndexes,
      totalEnums,
    },
    files: fileMetrics,
  };
}

export function formatMarkdown(metrics) {
  const lines = [];
  lines.push("# P12-026 Schema Measurement");
  lines.push("");
  lines.push("> **AUTOMATICALLY GENERATED BY `scripts/measure-schema.mjs`.**");
  lines.push("");
  lines.push("## Summary Metrics");
  lines.push("");
  lines.push(`- **Total Schema Files**: ${metrics.summary.totalFiles}`);
  lines.push(`- **Total Schema Lines**: ${metrics.summary.totalLines.toLocaleString()}`);
  lines.push(`- **Total Models**: ${metrics.summary.totalModels.toLocaleString()}`);
  lines.push(`- **Total Fields**: ${metrics.summary.totalFields.toLocaleString()}`);
  lines.push(`- **Total Relations**: ${metrics.summary.totalRelations.toLocaleString()}`);
  lines.push(`- **Total Indexes/Uniques**: ${metrics.summary.totalIndexes.toLocaleString()}`);
  lines.push(`- **Total Enums**: ${metrics.summary.totalEnums.toLocaleString()}`);
  lines.push("");
  lines.push("## File Breakdown");
  lines.push("");
  lines.push("| File | Lines | Models | Fields | Relations | Indexes | Enums | Size (KB) |");
  lines.push("| :--- | :---: | :----: | :----: | :-------: | :-----: | :---: | :--------: |");

  for (const [file, m] of Object.entries(metrics.files)) {
    lines.push(`| \`${file}\` | ${m.lines} | ${m.models} | ${m.fields} | ${m.relations} | ${m.indexes} | ${m.enums} | ${(m.bytes / 1024).toFixed(1)} |`);
  }

  lines.push("");
  return lines.join("\n");
}

const isGenerate = process.argv.includes("--generate");
const isVerify = process.argv.includes("--verify") || (!isGenerate && Boolean(process.argv[1]));

const metrics = measureEstateSchema();

if (isGenerate) {
  writeFileSync(JSON_OUT, JSON.stringify(metrics, null, 2) + "\n", "utf8");
  writeFileSync(MD_OUT, formatMarkdown(metrics), "utf8");
  console.log(`OK    Measured ${metrics.summary.totalModels} models across ${metrics.summary.totalFiles} files. Artifacts updated.`);
  process.exit(0);
}

if (isVerify) {
  if (!existsSync(JSON_OUT) || !existsSync(MD_OUT)) {
    console.error("FAIL  measure-schema: Artifacts missing. Run --generate.");
    process.exit(1);
  }

  const existingJson = JSON.parse(readFileSync(JSON_OUT, "utf8"));
  if (
    existingJson.summary.totalModels !== metrics.summary.totalModels ||
    existingJson.summary.totalFiles !== metrics.summary.totalFiles
  ) {
    console.error("FAIL  measure-schema: Schema measurement drift detected. Run `node scripts/measure-schema.mjs --generate` to synchronize.");
    process.exit(1);
  }

  console.log(`OK    Schema measurement verified: ${metrics.summary.totalModels} models across ${metrics.summary.totalFiles} schema files reproducible.`);
  process.exit(0);
}
